config/routes.rb
Rails.application.routes.draw do

  resources :feed_items

  resources :asks

  resources :tickets

  resources :special_links

  root 'static_pages#home'
  
  match '/tickets/:ticket_id/message', to: 'ticket_messages#create', via: 'post', as: :create_ticket_message

  match '/tickets/:ticket_id/message/:id', to: 'ticket_messages#destroy', via: 'delete', as: :ticket_message

  match '/tickets/:ticket_id/message/:id', to: 'ticket_messages#update', via: 'patch'

  match '/tickets/:ticket_id/message/:id', to: 'ticket_messages#update', via: 'put'

  match '/funds/:id/finish_fund', to: 'funds#finish_fund', via: 'get', as: :finish_fund

  resources :tickets do
    member do
      get 'close'
      get 'open'
    end
    resources :ticket_messages, only: [:create, :update, :destroy]
  end
  
  match '/list_news', to: 'feed_items#full_list', via: 'get'

  match '/news_feed', to: 'feed_items#index', via: 'get'

  match '/l/:special_link', to: 'special_links#record', via: 'get'

  match '/l/:special_link/:user_hash', to: 'special_links#record', via: 'get'

  match '/funds/current', to: 'funds#current', via: 'get'

  match '/funds/finished', to: 'funds#finished', via: 'get'

  match '/withdraw', to: 'users#withdraw_money', via: 'get'

  match '/settings/:id', to: 'users#edit', via: 'get'

  match '/settings', to: 'users#edit', via: 'get'

  match '/settings', to: 'users#update', via: 'patch'
  
  match '/settings', to: 'users#update', via: 'put'

  match '/invited_list/:id', to: 'users#invited_list', via: 'get'

  match '/invited_list', to: 'users#invited_list', via: 'get'

  match '/next', to: 'users#next_registration', via: 'get'

  match '/signup', to: 'users#new', via: 'get'

  match '/check_response', to: 'users#check_response', via: 'get'

  match '/signin', to: 'sessions#new', via: 'get'
  
  match '/signout', to: 'sessions#destroy', via: 'delete'

  match '/help', to: 'static_pages#help', via: 'get'

  match '/how_it_work', to: 'static_pages#how_it_work', via: 'get'
  
  match '/profile', to: 'static_pages#profile', via: 'get'

  match '/project_achievements', to: 'static_pages#project_achievements', via: 'get'

  match '/statistics', to: 'static_pages#statistics', via: 'get'

  resources :funds

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  before_action :signed_in_user, only: [:profile, :statistics, :help]
  
  before_action :admin_user, only: :statistics

  before_action :check_confirmation,  only: [:profile, :help]

  def home
      @newsFeed = FeedItem.prepared.order('created_at desc').paginate(page: params[:page], per_page: 5)
      redirect_to :profile if signed_in?
  end

  def profile
    @user = current_user
    @newsFeed = FeedItem.prepared.order('created_at desc').paginate(page: params[:page], per_page: 5)

    render 'users/profile'
  end

  def how_it_work
    @asks = Ask.where(ask_status: 1).order('priority DESC') 
  end

  def help
    @asks = Ask.where(ask_status: 1).order('priority DESC')
  end

  def project_achievements
    @user_count = User.count
  end

  def statistics

  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
	def hide_sidebar_for_nonsigned
		@hide_sidebar = true unless confirmed?
  	end

  	def always_hide_sidebar
		@hide_sidebar = true
  	end
end

app/views/static_pages/_for_nonsigned.html.erb
<% provide(:title, 'добро пожаловать!') %>
<div class="row">
	<div class="large-6 columns">
		<h3>Для чего этот сайт?</h3>
		<ul>
			<li>Небольшой зарабаток вам</li>
			<li>Передача части денег различным фондам помощи (15%)</li>
			<li>Передача части денег администратору сайта (5%)</li>
		</ul>
		<h3>Что нужно для участия?</h3>
		<ul>
			<li>Регистрация</li>
			<li>Единоразовый вклад 100 рублей</li>
		</ul>
	</div>

	<div class="large-6 columns">
		<h3>Как вы зарабатываете?</h3>
		<ul>
			<li>За каждого приглашённого вы получаете 50% от его вклада</li>
			<li>За всех кого приглашает, приглашённый вами, вы получаете 10% от их вклада</li>
			<li>И так ещё на 2 уровня!</li>
		</ul>
		<p>
<em><pre>
Пример:
вы пригласили Антона - вам 50 рублей после его вклада
Антон пригласил 4-х человек - вам 4x10 = 40 рублей
каждый из 4-х пригласил по 3 человека - вам 4х3х10 = 120 рублей
эти 3-е пригласили по 3 человека - вам 4х3х3х10 = 360 рублей
Итого 570 рублей, которые вы можете снять в любой момент,
А вы пригласили только одного Антона!
Также с данной цепочки на пользу текущего фонда пойдёт 540 рублей!
Вы заработали - вы помогли!
</pre></em>
		</p>
	</div>
</div>
<div class="row">
	<div class="large-3 large-centered columns text-center">
		<%= link_to('присоединиться', signup_path, class: 'button') %>
		Есть аккаунт? <%= link_to('Войти!', signin_path) %>
	</div>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, 'помощь') %>

<%= link_to "Как это работает?", how_it_work_path %>
<br />
<%= link_to "Написать тикет", new_ticket_path %>

<h4>Список часто задаваемых вопросов</h4>
<%= render partial: 'asks/ask', collection: @asks.all %>

<% if current_user.admin? %>
	<br />
	<%= link_to "редактируемый список вопросов", asks_path, class: "button" %>
<% end %>

app/views/static_pages/home.html.erb
<div class="row">
	<div id="land-image">
		<span class="land-item">
			<%= image_tag("invite1.jpg", alt: "", class: "land-image") %>
			<ul class="land-list">
				<li>Из твоих знакомых ещё никто не зарегистрировался? <%= link_to('Стань первым', signup_path) %> и заработай первым</li>
				<li>Зарегистрировавшись по приглашению, зарабатывай первую неделю больше - польза и тебе, и пригласившему</li>
				<li>Публикуй приглашения в социальных сетях</li>
			</ul>
			<span class="land-block">
			</span>
			<span class="land-thumb-over">
				<span class="land-thumb">
					<%= image_tag("land/city.png", alt: "Микро-вклад с неплохой прибылью", class: "land-showed") %>
					<span class="land-hidded">
						<%= image_tag("land/city2.png", alt: "Небольшой, но честный заработок простым способом") %>
					</span>
				</span>
			</span>
			<span class="land-text-bg"></span>
			<span class="land-text">
				<span class="land-text-first">
					Стань первым!
				</span>
				<span class="land-text-hidded">
					Приглашай друзей!
				</span>
			</span>
		</span>

		<span class="land-item">
			<%= image_tag("invite1.jpg", alt: "", class: "land-image") %>
			<ul class="land-list">
				<li>Снимай в любое время со своего счёта на карточку, мобильный или электронный кошелёк</li>
				<li>Следи за количеством присоединившихся к тебе, можешь посчитать прибыль сам</li>
				<li>Известная <%= link_to('платёжная система', 'http://robokassa.ru/ru/') %> - всё безопасно</li>
			</ul>
			<span class="land-block">
			</span>
			<span class="land-thumb-over">
				<span class="land-thumb">
					<%= image_tag("land/eye.png", alt: "Следи за заработком", class: "land-showed") %>
					<span class="land-hidded">
						<%= image_tag("land/eye2.png", alt: "Честный заработок") %>
					</span>
				</span>
			</span>
			<span class="land-text-bg"></span>
			<span class="land-text">
				<span class="land-text-first">
					Всё на виду!
				</span>
				<span class="land-text-hidded">
					Ничего не скрыто!
				</span>
			</span>
		</span>

		<span class="land-item">
			<%= image_tag("invite1.jpg", alt: "", class: "land-image") %>
			<ul class="land-list">
				<li>Каждую неделю в текущий фонд передаются все собранные средства и происходит смена</li>
				<li>Как минимум 10% за каждую активацию передаётся в текущий фонд</li>
				<li>Следи за количеством уже переданных средств на <%= link_to('странице фондов', funds_finished_path) %></li>
				<li>Знаешь о благотворительном фонде? <%= link_to('Предложи!', new_ticket_path) %></li>
			</ul>
			<span class="land-block">
			</span>
			<span class="land-thumb-over">
				<span class="land-thumb">
					<%= image_tag("land/hands.png", alt: "Благотворительность и заработок", class: "land-showed") %>
					<span class="land-hidded">
						<%= image_tag("land/hands2.png", alt: "Дари добро и зарабатывай") %>
					</span>
				</span>
			</span>
			<span class="land-text-bg"></span>
			<span class="land-text">
				<span class="land-text-first">
					Благое дело!
				</span>
				<span class="land-text-hidded">
					10% в фонды!
				</span>
			</span>
		</span>

		<span class="land-item">
			<%= image_tag("invite1.jpg", alt: "", class: "land-image") %>
			<ul class="land-list">
				<li>Приглашай и получай половину за активацию на свой счёт!</li>
				<li>Дополнительный заработок за приглашённых твоими друзями!</li>
				<li>И это не всё! Смотри <%= link_to('как это работает', how_it_work_path) %></li>
			</ul>
			<span class="land-block">
			</span>
			<span class="land-thumb-over">
				<span class="land-thumb">
					<%= image_tag("land/invite.png", alt: "Зови знакомых и получай доход", class: "land-showed") %>
					<span class="land-hidded">
						<%= image_tag("land/invite2.png", alt: "Приглашай и гарантированно зарабатывай") %>
					</span>
				</span>
			</span>
			<span class="land-text-bg"></span>
			<span class="land-text">
				<span class="land-text-first">
					Приглашай!
				</span>
				<span class="land-text-hidded">
					Зарабатывай!
				</span>
			</span>
		</span>
	</div>
</div>
	<div class="row text-center signup">
		<%= link_to "Присоединиться!", signup_path, { class: "medium radius button" } %>
	</div>
	<table class="info-block row">
		<tbody class="block">
			<tr>
				<td colspan="2" class="text-center">
					<h2>Как начать зарбатывать?</h2>
				</td>
			</tr>
			<tr>
				<td class="text-center">
					<%= image_tag("other/hands-invite.png", alt: "hands-invite") %>
				</td>
				<td>
					<div class="border">
						<ol>
							<li><%= link_to "Присоединись", signup_path %> и активируй аккаунт за 100 рублей</li>
							<li>Приглашай всех по личной ссылке - получай по 50 рублей за каждого активированного по ней и не только!</li>
							<li>Перечисли деньги на свой счёт в любой момент! (телефон, карточка или электронный кошелёк)</li>
						</ol>
					</div>
				</td>
			</tr>
		</tbody>
		<tr class="spacer"><td></td></tr>
		<tbody class="block">
			<tr>
				<td colspan="2" class="text-center">
					<h2>Благотворительность</h2>
				</td>
			</tr>
			<tr>
				<td>
					<div class="border">
						<ol>
							<li>Как минимум 10% от каждой активации передаётся текущему фонду</li>
							<li>Прослеживай <%= link_to('списки фондов', funds_finished_path) %>, которым уже помогли</li>
							<li>Узнай сколько денег накопилось у <%= link_to 'текущего фонда', funds_current_path %></li>
						</ol>
					</div>
				</td>
				<td class="text-center">
					<%= image_tag("other/heart.png", alt: "heart") %>
				</td>
			</tr>
		</tbody>
	</table>
	<br />
<hr >
<%= render 'feed_items/list' %>
<%= will_paginate(@newsFeed) %>
<%= javascript_include_tag "land" %>

app/views/static_pages/how_it_work.html.erb
<% provide(:title, 'о проекте') %>
<%= stylesheet_link_tag    "dub/css.scss" %>

<h4>Happy Tree</h4>
<div class="panel">
	<p>
		&emsp;Проект, который может обеспечить небольшой, но не рискованный зарабаток в Инетрнете. Вы оплачиваете активацию аккаунта и получаете возможность приглашать знакомых, публикуя приглашение в социальные сети или отправляя любым способом личный код-приглашение. За активацию приглашённых вы получаете начисления в виде 50 рублей и не только! Отличительные особенности проекта:
		<ul id="features-list">
			<li>активация аккаунта - единоразовый платёж 100 рублей</li>
			<li>часть платежа отправляется на счёт благотворительного фонда</li>
			<li>приглашённый вами получает <span data-tooltip aria-haspopup="true" class="has-tip" title="Первую неделю приглашённый за счёт администратора будет получать +5 рублей за каждую активацию приглашённых им.">бонус</span>, что мотивирует регистрацию по вашему приглашению</li>
		</ul>
	</p>
</div>
<table id="get-money">
	<tr>
		<td>
			<h4>Зарабатывайте</h4>
			<ul id="fund-info-list" class="circle">
				<li>Пригалашайте друзей и получайте за каждого активированного по 50 рублей</li>
				<li>За каждую активацию приглашённых вашими друзьями Вы также получаете по 10 рублей</li>
				<li>Получайте дополнительно по 10 рублей за активированных далее, вплоть до 4 уровня приглашений (отображено на рисунке кругами)</li>
				<li>На рисунке справа отображено как примерно может выглядеть ваша ветка, пригласи Вы всего 2-х человек (уже 320 рублей заработка)</li>
			</ul>
		</td>
		<td>
			<%= image_tag("dub/tree.png", alt: "Зарабаток из микро-вклада с элементами благотворительности!") %>
		</td>
	</tr>
</table>
<hr />
<table id="fund-info">
	<tr>
		<td>
			<div id="fund-animation">
				<div id="fund-dub"></div>
				<div id="fund-dub-bot"></div>
			</div>
			<div class="progress secondary radius">
				<span class="text">смена фонда</span>
				<span id="fund-info-meter" class="meter" style="width: 0%">
				</span>
				<div class="textWeek">неделя</div>
			</div>
		</td>
		<td>
			<h4>Благотворительные фонды</h4>
			<ul id="fund-info-list" class="circle">
				<li>Корнем всего дерева является благотворительный фонд, который сменяется раз в неделю</li>
				<li>В течение недели фонд будет накапливать денежные средства от активаций пользователей</li>
				<li>Накопленные для фонда средства отправляются на его счёт, и на сайте публикуется информация о перечислении</li>
			</ul>
		</td>
	</tr>
</table>


<h4>Список часто задаваемых вопросов</h4>
<%= render partial: 'asks/ask', collection: @asks.all %>
<%= javascript_include_tag "dub" %>

app/views/static_pages/project_achievements.html.erb
<% provide(:title, 'достижения проекта') %>

<div class="large-8 large-centered columns">
	<h1>Достижения проекта</h1>
	<table width="100%">
	<% unless User.first.nil? %>
	<tr>
		<td>
			Времени прошло с момента запуска
		</td>
		<td>
			<%= ((Time.now - User.first.created_at) / (60 * 60 * 24)).to_i %>
			<%= Russian.p(((Time.now - User.first.created_at) / (60 * 60 * 24)).to_i, 'день', 'дня', 'дней') %>
		</td>
	</tr>
	<% end %>
	<tr>
		<td>
			Количество присоединившихся
		</td>
		<td>
			<%= @user_count %>
		</td>
	</tr>
	<tr>
		<td>
			Количество активированных
		</td>
		<td>
			<%= User.where(confirmed: true).count %>
		</td>
	</tr>
	<!-- <tr>
		<td>
			Средний вклад
		</td>
		<td>
			<%= User.average(:deposit) %>
		</td>
	</tr> -->
	<tr>
		<td>
			Количество фондов, которым помогли
		</td>
		<td>
			<%= Fund.where(finished: 1).count %>
		</td>
	</tr>
	<tr>
		<td>
			Всего отправлено в фонды
		</td>
		<td>
			<%= Fund.sum(:result) + Fund.sum(:result_other) %>
		</td>
	</tr>
	</table>
</div>

app/views/static_pages/statistics.html.erb
<% provide(:title, 'статистика и графика') %>

<h2>Общее количество пользователей</h2>
<%= line_chart User.group_by_day(:created_at).count %>

<h2>Подтверждённые пользователи - колонка приглашения</h2>
<div class="row">
	<div class="small-10 columns">
		<%= line_chart [
			{ name: "Админ", data: User.where("inviter_id IS ? AND confirmed = true", nil).group_by_day(:created_at).count },
			{ name: "Приглашён", data: User.where("inviter_id IS NOT ? AND confirmed = true", nil).group_by_day(:created_at).count }
			] %>
	</div>
	<div class="small-2 columns">
		<%= pie_chart ({"Админ" => User.where("inviter_id IS ? AND confirmed = true", nil).count,
			"Приглашён" => User.where("inviter_id IS NOT ? AND confirmed = true", nil).count}) %>
	</div>
</div>

<h2>График регистрации - колонка приглашения</h2>
<div class="row">
	<div class="small-10 columns">
		<%= line_chart [
			{ name: "Админ", data: User.where("inviter_id IS ?", nil).group_by_day(:created_at).count },
			{ name: "Приглашён", data: User.where("inviter_id IS NOT ?", nil).group_by_day(:created_at).count }
			] %>
	</div>
	<div class="small-2 columns">
		<%= pie_chart ({"Админ" => User.where("inviter_id IS ?", nil).count,
			"Приглашён" => User.where("inviter_id IS NOT ?", nil).count}) %>
	</div>
</div>

<h2>Средний депозит</h2>
<%= area_chart User.group_by_day(:created_at).average(:deposit) %>


<script>
  var Chartkick = {"language": "ru"};
</script>