config/routes.rb
Rails.application.routes.draw do

  resources :feed_items

  resources :asks

  resources :tickets

  resources :special_links

  root 'static_pages#home'
  
  match '/tickets/:ticket_id/message', to: 'ticket_messages#create', via: 'post', as: :create_ticket_message

  match '/tickets/:ticket_id/message/:id', to: 'ticket_messages#destroy', via: 'delete', as: :ticket_message

  match '/tickets/:ticket_id/message/:id', to: 'ticket_messages#update', via: 'patch'

  match '/tickets/:ticket_id/message/:id', to: 'ticket_messages#update', via: 'put'

  match '/funds/:id/finish_fund', to: 'funds#finish_fund', via: 'get', as: :finish_fund

  resources :tickets do
    member do
      get 'close'
      get 'open'
    end
    resources :ticket_messages, only: [:create, :update, :destroy]
  end
  
  match '/list_news', to: 'feed_items#full_list', via: 'get'

  match '/news_feed', to: 'feed_items#index', via: 'get'

  match '/l/:special_link', to: 'special_links#record', via: 'get'

  match '/l/:special_link/:user_hash', to: 'special_links#record', via: 'get'

  match '/funds/current', to: 'funds#current', via: 'get'

  match '/funds/finished', to: 'funds#finished', via: 'get'

  match '/withdraw', to: 'users#withdraw_money', via: 'get'

  match '/settings/:id', to: 'users#edit', via: 'get'

  match '/settings', to: 'users#edit', via: 'get'

  match '/settings', to: 'users#update', via: 'patch'
  
  match '/settings', to: 'users#update', via: 'put'

  match '/invited_list/:id', to: 'users#invited_list', via: 'get'

  match '/invited_list', to: 'users#invited_list', via: 'get'

  match '/next', to: 'users#next_registration', via: 'get'

  match '/signup', to: 'users#new', via: 'get'

  match '/check_response', to: 'users#check_response', via: 'get'

  match '/signin', to: 'sessions#new', via: 'get'
  
  match '/signout', to: 'sessions#destroy', via: 'delete'

  match '/help', to: 'static_pages#help', via: 'get'

  match '/how_it_work', to: 'static_pages#how_it_work', via: 'get'
  
  match '/profile', to: 'static_pages#profile', via: 'get'

  match '/project_achievements', to: 'static_pages#project_achievements', via: 'get'

  match '/statistics', to: 'static_pages#statistics', via: 'get'

  resources :funds

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
	belongs_to :creater, foreign_key: "user_id", class_name: "User"
	has_many :ticket_messages,  dependent: :destroy
	accepts_nested_attributes_for :ticket_messages,
		:allow_destroy => true

	validates :title, presence: true, length: { minimum: 6, maximum: 200 }
	validates :content, presence: true, length: { minimum: 20, maximum: 1800 }
	validates :priority, presence: true
	validates :user_id, presence: true
	validate :priority_validate

	CLOSED = 0
	USER_WAIT = 1
	ADMIN_WAIT = 2

	before_create do
		self.ticket_status = USER_WAIT if self.ticket_status.nil?
		self.priority = 0 if self.priority.nil?
	end

	def closed?
		self.ticket_status == CLOSED
	end

	def set_status_by_user(user_id)
		user = User.find(user_id)
		if user.admin?
			self.ticket_status = USER_WAIT
		else
			self.ticket_status = ADMIN_WAIT
		end
	end

	def Ticket.closed(user_id)
		Ticket.where('user_id = ? AND ticket_status = ?', user_id, CLOSED)
	end

	def Ticket.opened(user_id)
		Ticket.where('user_id = ? AND ticket_status != ?', user_id, CLOSED)
	end

	def Ticket.opened_to_admin(user_id)
		Ticket.where('user_id = ? AND ticket_status = ?', user_id, USER_WAIT)
	end

	def Ticket.opened_to_user(user_id)
		Ticket.where('user_id = ? AND ticket_status = ?', user_id, ADMIN_WAIT)
	end

	private
		def priority_validate
			unless self.priority.nil?
				errors.add(:priority, "неверный приоритет") unless self.priority.between?(CLOSED, ADMIN_WAIT + 1)
			end
		end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :signed_in_user
  before_action :admin_user,          except: [:new, :index, :show, :create, :close, :open]
  before_action :check_confirmation

  before_action :set_ticket,          only: [:show, :edit, :update, :destroy, :open, :close]
  before_action :set_ticket_message,  only: [:show]
  before_action :only_current_user,   only: [:show, :close, :open]

  # GET /tickets
  # GET /tickets.json
  def index
    if current_user.admin?
      @tickets = Ticket.all.order('ticket_status desc, priority desc, created_at desc')
    else
      @tickets = current_user.tickets.order('ticket_status desc, priority desc, created_at desc')
    end
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  def close
    @ticket.update(ticket_status: 0)
    redirect_to @ticket
  end

  def open
    @ticket.update(ticket_status: 1)
    redirect_to @ticket
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.user_id = current_user.id

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_ticket_message
      @ticket_message = @ticket.ticket_messages.new
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:title, :content, :priority)
    end

    def only_current_user
      unless current_user.id == @ticket.user_id
        unless current_user.admin?
          redirect_to(root_url)
        end
      end
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
	def get_ticket_status_message(status)
		case status
				when 0
					"тикет закрыт"
				when 1
					"ожидается ответ пользователя"
				when 2
					"ожидается ответ администратора"
				else
					"неизвестно"
				end
	end

	def get_ticket_priority_message(priotiry)
		case priotiry
			when 0
				"низкий"
			when 1
				"средний"
			when 2
				"высокий"
			else
				"неизвестно"
		end
	end
end

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="large-10 columns">
      <label>
        <%= f.label :title %>
        <%= f.text_field :title %>
      </label>
    </div>
    <div class="large-2 columns">
      <label>
        <%= f.label :priority %>
        <%= f.select(:priority, options_for_select((0..2).map { |i| [get_ticket_priority_message(i), i] })) %>
      </label>
    </div>
  </div>
  <div class="row">
    <div class="large-12 columns">
      <label>
        <%= f.label :content %>
        <%= f.text_area :content %>
      </label>
    </div>
  </div>

  <div class="row">
    <div class="large-12 columns">
      <%= submit_tag "Сохранить", :class => "button" %>
    </div>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Редактировать тикет</h1>

<%= render 'form' %>

<%= link_to 'Перейти к диалогу', @ticket %>

app/views/tickets/index.html.erb
<h1>Список тикетов</h1>

<table class="large-12">
  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td>
          <h3><%= link_to ticket.title, ticket %></h3>
          <p><%= ticket.content %></p>
          Тикет создан <%= ticket.created_at.localtime.strftime("%d.%m.%y в %H:%M") %>
          <ul class="no-bullet">
            <li>
              Приоритет <%= get_ticket_priority_message(ticket.priority) %>
            </li>
            <li>
              Статус: <%= get_ticket_status_message(ticket.ticket_status) %>
            </li>
            <% if current_user.admin? %>
              <li>
                  <% unless ticket.user_id.nil? %>
                    Пользователь <%= link_to User.find(ticket.user_id).login, User.find(ticket.user_id) %>
                  <% end %>
              </li>
              <li>
                <%= link_to 'Редактировать', edit_ticket_path(ticket) %>
              </li>
              <li>
                <%= link_to 'Удалить', ticket, method: :delete, data: { confirm: 'Точно?' } %>
              </li>
            <% end %>
          </ul>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>Новый тикет</h1>

<%= render 'form' %>

<%= link_to 'Назад', tickets_path %>

app/views/tickets/show.html.erb
<% provide(:title, "тикет ##{@ticket.id} - #{@ticket.title}") %>

<div data-alert class="alert-box info">
  <h2>
    <%= @ticket.title %>
  </h2>

  <p>
    <%= @ticket.content %>
  </p>

  <div>
    <label>Приоритет
    <%= get_ticket_priority_message(@ticket.priority) %>
    </label>
  </div>

  <div>
    Статус:
    <%= get_ticket_status_message(@ticket.ticket_status) %>
  </div>

  <% if current_user.admin? %>
  <div>
    Пользователь
    <%= link_to User.find(@ticket.user_id).login, User.find(@ticket.user_id) %>
  </div>
  <% end %>
</div>

  
<%= render partial: 'ticket_messages/ticket_message', collection: @ticket.ticket_messages.all %>

<% unless @ticket.closed? %>
  <%= render 'ticket_messages/form' %>
<% end %>

<% if @ticket.closed? %>
  <%= link_to 'Есть вопрос', open_ticket_path(@ticket), class: "button small secondary" %>
<% else %>
  <%= link_to 'Вопрос решён', close_ticket_path(@ticket), class: "button small secondary" %>
<% end %>

<% if current_user.admin? %>
  <%= link_to 'редактировать', edit_ticket_path(@ticket), class: "button small secondary" %>
<% end %>
<%= link_to 'список тикетов', tickets_path, class: "button small secondary" %>