config/routes.rb
Rails.application.routes.draw do

  resources :feed_items

  resources :asks

  resources :tickets

  resources :special_links

  root 'static_pages#home'
  
  match '/tickets/:ticket_id/message', to: 'ticket_messages#create', via: 'post', as: :create_ticket_message

  match '/tickets/:ticket_id/message/:id', to: 'ticket_messages#destroy', via: 'delete', as: :ticket_message

  match '/tickets/:ticket_id/message/:id', to: 'ticket_messages#update', via: 'patch'

  match '/tickets/:ticket_id/message/:id', to: 'ticket_messages#update', via: 'put'

  match '/funds/:id/finish_fund', to: 'funds#finish_fund', via: 'get', as: :finish_fund

  resources :tickets do
    member do
      get 'close'
      get 'open'
    end
    resources :ticket_messages, only: [:create, :update, :destroy]
  end
  
  match '/list_news', to: 'feed_items#full_list', via: 'get'

  match '/news_feed', to: 'feed_items#index', via: 'get'

  match '/l/:special_link', to: 'special_links#record', via: 'get'

  match '/l/:special_link/:user_hash', to: 'special_links#record', via: 'get'

  match '/funds/current', to: 'funds#current', via: 'get'

  match '/funds/finished', to: 'funds#finished', via: 'get'

  match '/withdraw', to: 'users#withdraw_money', via: 'get'

  match '/settings/:id', to: 'users#edit', via: 'get'

  match '/settings', to: 'users#edit', via: 'get'

  match '/settings', to: 'users#update', via: 'patch'
  
  match '/settings', to: 'users#update', via: 'put'

  match '/invited_list/:id', to: 'users#invited_list', via: 'get'

  match '/invited_list', to: 'users#invited_list', via: 'get'

  match '/next', to: 'users#next_registration', via: 'get'

  match '/signup', to: 'users#new', via: 'get'

  match '/check_response', to: 'users#check_response', via: 'get'

  match '/signin', to: 'sessions#new', via: 'get'
  
  match '/signout', to: 'sessions#destroy', via: 'delete'

  match '/help', to: 'static_pages#help', via: 'get'

  match '/how_it_work', to: 'static_pages#how_it_work', via: 'get'
  
  match '/profile', to: 'static_pages#profile', via: 'get'

  match '/project_achievements', to: 'static_pages#project_achievements', via: 'get'

  match '/statistics', to: 'static_pages#statistics', via: 'get'

  resources :funds

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/fund.rb
class Fund < ActiveRecord::Base
	validates :name, presence: true, length: { minimum: 5, maximum: 220 }
	validates :content, presence: true, length: { minimum: 5, maximum: 800 }
	validates :begin_time, presence: true
	validates :end_time, presence: true
	validate :check_time_begin_greate_end, unless: :skip_callbacks
	validate :check_time_intersection, unless: :skip_callbacks
	validate :check_time_old, on: :create, unless: :skip_callbacks

	before_create do
		self.finished = 0
		self.result = 0
		self.result_other = 0
	end

	def Fund.add_to_current(money)
		result = Fund.where("begin_time < ? AND end_time > ?", Time.now, Time.now).first()

		if result.nil?		
			result = Fund.where("begin_time < ?", Time.now).last

			if result.nil?
				result = Fund.last

				if result.nil?
					User.first.update_attribute(:capital, User.first.capital + money)
					return
				end
			end
		end

		result.update_attribute(:result, result.result + money)

	end

	# последний фонд, которому была оказана помощь
	def Fund.last_helped
		Fund.where("end_time < ?", Time.now).order(:end_time).last()
	end

	def Fund.finished
		Fund.where("end_time < ?", Time.now).order(:end_time)
	end

	def Fund.non_finished
		Fund.where("end_time > ?", Time.now).order(:begin_time)
	end

	def finish_it
		self.update_attribute(:finished, 1)
	end

	private
		def check_time_begin_greate_end
			if self.begin_time > self.end_time
				errors.add(:begin_time, 
					"дата начала не может быть позже даты окончания")
			end
		end

		def check_time_old
			if self.begin_time < Date.today
				errors.add(:begin_time, 
					"дата начала не может быть раньше текущего дня")
			end
		end

		def check_time_intersection
			b = self.begin_time
			e = self.end_time

			intesect_begin = 
			Fund.where("begin_time < ? AND end_time > ?", b, b).first()

    		intesect_end = 
    		Fund.where("begin_time < ? AND end_time > ?", e, e).first()

    		unless intesect_begin.nil?
    			errors.add(:begin_time, 
					"дата начала пересекается с датой уже добавленного фонда '#{intesect_begin.name}'
					(#{intesect_begin.begin_time} - #{intesect_begin.end_time})")
    		end

    		unless intesect_end.nil?
    			errors.add(:end_time, 
					"дата окончания пересекается с датой уже добавленного фонда '#{intesect_end.name}'
					(#{intesect_end.begin_time} - #{intesect_end.end_time})")
    		end
		end
end

app/controllers/funds_controller.rb
class FundsController < ApplicationController
  before_action :signed_in_user,   except: [:current, :finished]
  before_action :admin_user,       except: [:current, :finished]
  before_action :set_fund,         only: [:show, :edit, :update, :destroy, :finish_fund]

  # GET /funds
  # GET /funds.json
  def index
    @funds = Fund.all.paginate(page: params[:page], per_page: 5)
  end

  # GET /funds/1
  # GET /funds/1.json
  def show
  end

  def current
    @fund = Fund.
    where("begin_time < ? AND end_time > ?", Time.now, Time.now).
    first()

    @last_helped = Fund.last_helped

    @current = true
    
    render 'show'
  end

  def finished
    @funds = Fund.finished.paginate(page: params[:page], per_page: 5)
  end

  def finish_fund
  end

  # GET /funds/new
  def new
    @fund = Fund.new
  end

  # GET /funds/1/edit
  def edit
  end

  # POST /funds
  # POST /funds.json
  def create
    @fund = Fund.new(fund_params)

    respond_to do |format|
      if @fund.save
        format.html { redirect_to @fund, notice: 'Fund was successfully created.' }
        format.json { render :show, status: :created, location: @fund }
      else
        format.html { render :new }
        format.json { render json: @fund.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funds/1
  # PATCH/PUT /funds/1.json
  def update
    respond_to do |format|
      if @fund.update(fund_params)
        format.html { redirect_to @fund, notice: 'Fund was successfully updated.' }
        format.json { render :show, status: :ok, location: @fund }
      else
        format.html { render :edit }
        format.json { render json: @fund.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funds/1
  # DELETE /funds/1.json
  def destroy
    @fund.destroy
    respond_to do |format|
      format.html { redirect_to funds_url, notice: 'Fund was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fund
      @fund = Fund.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fund_params
      params.require(:fund).permit(:name, :content, :ewallet, :response, :result, :result_other, :finished, :begin_time, :end_time)
    end
end

app/helpers/funds_helper.rb
module FundsHelper
end

app/views/funds/_form.html.erb
<%= form_for(@fund) do |f| %>
  <% if @fund.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fund.errors.count, "error") %> prohibited this fund from being saved:</h2>

      <ul>
      <% @fund.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="large-12 columns">
      <label>
        <%= f.label :name %>
        <%= f.text_field :name %>
      </label>
    </div>
  </div>
  <div class="row">
    <div class="large-12 columns">
      <label>
        <%= f.label :content %>
        <%= f.text_area :content %>
      </label>
    </div>
  </div>
  <div class="row">
    <div class="large-12 columns">
      <label>
        <%= f.label :ewallet %>
        <%= f.text_field :ewallet %>
      </label>
    </div>
  </div>
  <div class="row">
    <div class="large-6 columns">
      <label>
        <%= f.label :begin_time %>
        <%= f.date_select(:begin_time, default: Date.today + 7,         
                        :order => [:day, :month, :year]) %>
      </label>
    </div>
    <div class="large-6 columns">
      <label>
        <%= f.label :end_time %>
        <%= f.date_select(:end_time, :default => Date.today + 14,         
                        :order => [:day, :month, :year]) %>
      </label>
    </div>
  </div>
  <div class="row">
    <div class="large-12 columns">
      <%= submit_tag "Сохранить", :class => "button" %>
    </div>
  </div>
<% end %>

app/views/funds/_nothing.html.erb
<div class="alert-box">
  Ещё ни один фонд не был добавлен.
</div>

app/views/funds/edit.html.erb
<h1>Editing fund</h1>

<%= render 'form' %>

<%= link_to 'Show', @fund %> |
<%= link_to 'Back', funds_path %>

app/views/funds/finish_fund.html.erb
  <% provide(:title, "звершить активность фонда") %>

  <%= form_for(@fund) do |f| %>
  <% if @fund.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fund.errors.count, "error") %> prohibited this ask from being saved:</h2>

      <ul>
      <% @fund.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="large-12 columns">
      <label>
        <%= f.label :response, "Ответ" %><br>
        <%= f.text_area :response %>
      </label>
    </div>
  </div>
  <div class="row">
    <div class="large-12 columns">
      <label>
        <%= f.label :result_other, "Перечислено дополнительно" %>
        <%= f.text_field :result_other %>
      </label>
    </div>
  </div>
  <%= f.hidden_field :finished, value: 1 %>
  <div class="row">
    <div class="large-12 columns">
      <%= submit_tag "Сохранить", :class => "button" %>
    </div>
  </div>
<% end %>

app/views/funds/finished.html.erb
<% provide(:title, 'фонды, которым помогли') %>

<h3>Список фондов, которым уже оказана помощь</h3>

<% if @funds.length > 0 %>
<table>
  <tbody>
    <% @funds.each do |fund| %>
      <tr>
        <td>
          <h4><%= fund.name %></h4>
          <p><%= fund.content %></p>
          <table>
            <tr>
              <td><b>Кошелёк:</b></td>
              <td><%= fund.ewallet %></td>
            </tr>
            <tr>
              <td><b>Накоплено:</b></td>
              <td><%= fund.result %></td>
            </tr>
            <tr>
              <td><b>Время действия:</b></td>
              <td><%= fund.begin_time.strftime("%e %B %Y") %> - <%= fund.end_time.strftime("%e %B %Y") %></td>
            </tr>
            <% if fund.finished %>
              <tr>
                <td><b>Ответ:</b></td>
                <td><%= fund.response %></td>
              </tr>
            <% end %>
          </table>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
<div class="alert-box">
  Ещё ни один фонд не был добавлен.
</div>
<% end %>

<%= will_paginate(@funds) %>

app/views/funds/index.html.erb
<% provide(:title, 'управление фондами') %>

<h1>Список фондов</h1>

<% if @funds.length > 0 %>
<table>
  <tbody>
    <% @funds.each do |fund| %>
      <tr>
        <td>
          <h4><%= fund.name %></h4>
          <p><%= articlate(fund.content, 300, fund) %></p>
          <table>
            <tr>
              <td><b>Кошелёк:</b></td>
              <td><%= fund.ewallet %></td>
            </tr>
            <tr>
              <td><b>Накоплено:</b></td>
              <td><%= fund.result %></td>
            </tr>
            <tr>
              <td><b>Время действия:</b></td>
              <td><%= fund.begin_time.strftime("%e %B %Y") %> - <%= fund.end_time.strftime("%e %B %Y") %></td>
            </tr>
            <% if fund.finished %>
              <tr>
                <td><b>Ответ:</b></td>
                <td><%= fund.response %></td>
              </tr>
            <% end %>
            <tr>
              <td></td>
              <td>
                <ul class="inline-list">
                  <li><%= link_to 'Подробнее', fund %></li>
                  <li><%= link_to 'Редактировать', edit_fund_path(fund) %></li>
                  <li><%= link_to 'Удалить', fund, method: :delete, data: { confirm: 'Вы уверены?' } %></li>
                </ul>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
<div class="alert-box">
  Ни одного фонда не было добавлено.
</div>
<% end %>

<br>

<%= link_to 'New Fund', new_fund_path, { class: "button" } %>

<%= will_paginate(@funds) %>

app/views/funds/new.html.erb
<% provide(:title, "добавить фонд") %>

<h1>Новый фонд</h1>

<%= render 'form' %>

<%= link_to 'Назад', funds_path %>

app/views/funds/show.html.erb
<%= link_to 'Список фондов, которым уже помогли', funds_finished_path %>
<% unless @fund.nil? %>
  <% provide(:title, @fund.name) %>
  
  <p id="notice"><%= notice %></p>

  <h2>
    <%= @fund.name %>
  </h2>

  <p>
    <%= @fund.content %>
  </p>

  <table>
    <tr>
      <td><b>Кошелёк:</b></td>
      <td><%= @fund.ewallet %></td>
    </tr>
    <tr>
      <td><b>Накоплено:</b></td>
      <td><%= @fund.result %></td>
    </tr>
    <tr>
      <td><b>Время действия:</b></td>
      <td><%= @fund.begin_time.strftime("%e %B %Y") %> - <%= @fund.end_time.strftime("%e %B %Y") %></td>
    </tr>
    <% if @fund.finished %>
      <tr>
        <td><b>Ответ:</b></td>
        <td><%= @fund.response %></td>
      </tr>
    <% end %>
    <% if current_user && current_user.admin? %>
      <tr>
        <td></td>
        <td>
          <ul class="inline-list">
            <li><%= link_to 'Подробнее', @fund %></li>
            <li><%= link_to 'Редактировать', edit_fund_path(@fund) %></li>
            <li><%= link_to 'Удалить', @fund, method: :delete, data: { confirm: 'Вы уверены?' } %></li>
          </ul>
        </td>
      </tr>
  <% end %>
  </table>

<% if @current && !@last_helped.nil? %>
  <h4>Последний фонд, которому была оказана помощь</h4>
  <h4>
    <%= @last_helped.name %>
  </h4>

  <p>
    <%= @last_helped.content %>
  </p>

  <table>
    <tr>
      <td><b>Кошелёк:</b></td>
      <td><%= @last_helped.ewallet %></td>
    </tr>
    <tr>
      <td><b>Накоплено:</b></td>
      <td><%= @last_helped.result %></td>
    </tr>
    <% if @last_helped.result_other > 0 %>
    <tr>
      <td><b>Накоплено дополнительно:</b></td>
      <td><%= @last_helped.result_other %></td>
    </tr>
    <% end %>
    <tr>
      <td><b>Время действия:</b></td>
      <td><%= @last_helped.begin_time.strftime("%e %B %Y") %> - <%= @last_helped.end_time.strftime("%e %B %Y") %></td>
    </tr>
    <% if @last_helped.finished && !@last_helped.response.nil? %>
      <tr>
        <td><b>Ответ:</b></td>
        <td><%= @last_helped.response %></td>
      </tr>
    <% end %>
    <% if current_user && current_user.admin? && !@last_helped.finished %>
      <tr>
        <td></td>
        <td>
          <ul class="inline-list">
            <li><%= link_to 'Перейти к завершению', finish_fund_path(@last_helped) %></li>
          </ul>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>
<% else %>
  <%= render 'nothing' %>
<% end %>