config/routes.rb
Rails.application.routes.draw do

  resources :feed_items

  resources :asks

  resources :tickets

  resources :special_links

  root 'static_pages#home'
  
  match '/tickets/:ticket_id/message', to: 'ticket_messages#create', via: 'post', as: :create_ticket_message

  match '/tickets/:ticket_id/message/:id', to: 'ticket_messages#destroy', via: 'delete', as: :ticket_message

  match '/tickets/:ticket_id/message/:id', to: 'ticket_messages#update', via: 'patch'

  match '/tickets/:ticket_id/message/:id', to: 'ticket_messages#update', via: 'put'

  match '/funds/:id/finish_fund', to: 'funds#finish_fund', via: 'get', as: :finish_fund

  resources :tickets do
    member do
      get 'close'
      get 'open'
    end
    resources :ticket_messages, only: [:create, :update, :destroy]
  end
  
  match '/list_news', to: 'feed_items#full_list', via: 'get'

  match '/news_feed', to: 'feed_items#index', via: 'get'

  match '/l/:special_link', to: 'special_links#record', via: 'get'

  match '/l/:special_link/:user_hash', to: 'special_links#record', via: 'get'

  match '/funds/current', to: 'funds#current', via: 'get'

  match '/funds/finished', to: 'funds#finished', via: 'get'

  match '/withdraw', to: 'users#withdraw_money', via: 'get'

  match '/settings/:id', to: 'users#edit', via: 'get'

  match '/settings', to: 'users#edit', via: 'get'

  match '/settings', to: 'users#update', via: 'patch'
  
  match '/settings', to: 'users#update', via: 'put'

  match '/invited_list/:id', to: 'users#invited_list', via: 'get'

  match '/invited_list', to: 'users#invited_list', via: 'get'

  match '/next', to: 'users#next_registration', via: 'get'

  match '/signup', to: 'users#new', via: 'get'

  match '/check_response', to: 'users#check_response', via: 'get'

  match '/signin', to: 'sessions#new', via: 'get'
  
  match '/signout', to: 'sessions#destroy', via: 'delete'

  match '/help', to: 'static_pages#help', via: 'get'

  match '/how_it_work', to: 'static_pages#how_it_work', via: 'get'
  
  match '/profile', to: 'static_pages#profile', via: 'get'

  match '/project_achievements', to: 'static_pages#project_achievements', via: 'get'

  match '/statistics', to: 'static_pages#statistics', via: 'get'

  resources :funds

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

end

app/views/layouts/_footer.html.erb
<div class="large-6 columns">
	<span class="copyright">© 2015 Jeshio, Happy Tree</span>
</div>
<div class="large-6 columns">
	<ul class="menu inline-list">
		<% if confirmed? %>
			<% if current_user.admin? %>
			<li><%= link_to "Список тикетов", tickets_path %></li>
			<% else %>
			<li><%= link_to "Написать тикет", new_ticket_path %></li>
			<% end %>
			<li><%= link_to('Помощь', help_path) %></li>
			<% unless current_user.opened_tickets.empty? %>
		      <li>
		        <%= link_to('Открытые тикеты', tickets_path) %>
		      </li>
		    <% end %>
		<% end %>
	</ul>
</div>

app/views/layouts/_side_bar.html.erb
<div class="large-3 columns side-bar">
    <ul class="side-nav">
      <li>
        <h4 class="subheader">текущий зарабаток</h4>
        <h4 class="subheader"><%= current_user.capital %> руб</h4>
        <% if current_user.capital > 0 %>
        <%= link_to 'Снять со счёта', withdraw_path %>
        <% end %>
      </li>
      <li>
      	<h4 class="subheader">приглашено всего</h4>
        <h4 class="subheader"><%= current_user.childrens.count %></h4>
      </li>
      <% unless current_user.opened_tickets.empty? %>
      <li>
        <h4 class="subheader">Тикеты</h4>
        <% current_user.opened_tickets.each do |ticket| %>
        <div>
          <%= link_to ticket.title, ticket %>
        </div>
        <div>
          - <i><%= get_ticket_status_message(ticket.ticket_status) %></i>
        </div>
        <% end %>
      </li>
      <% end %>
      <li class="text-center">
        50% сборов от рекламы за неделю передётся текущему фонду
      </li>
      <li>
      	<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <!-- HappyTree -->
        <ins class="adsbygoogle"
             style="display:inline-block;width:220px;height:400px"
             data-ad-client="ca-pub-1917630562772276"
             data-ad-slot="3206387352"></ins>
        <script>
        (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
      </li>
    </ul>
</div>

app/views/layouts/_top_bar.html.erb
<div class="contain-to-grid sticky">
  <nav class="top-bar" data-topbar  role="navigation" data-options="sticky_on: large">
    <section class="top-bar-section">
      <div class="left-side">
        <ul class="right">
          <li>
            <%= link_to('Текущий фонд', funds_current_path) %>
          </li>
          <li>
            <%= link_to('Достижения проекта', project_achievements_path) %>
          </li>
          <% if confirmed? %>
            <!-- 
            <li>
            <%= link_to('Рейтинг', "#") %>
            </li> -->
          <% end %>
        </ul>
      </div>
      <ul class="title-area">
        <li class="name">
            <%= link_to root_url do %>
              <div id='logo'></div>
            <% end %>
        </li>
      </ul>
      <div class="right-side">
        <ul class="left">
          <% if confirmed? %>
          <li class="has-dropdown">
            <a href="#">Пригласить</a>
            <ul class="dropdown share-list">
              <li class="share-line">
                <%= label_tag :share, 'Поделиться' %>
                <a href="<%= get_special_link('vkontakte', current_user.user_hash) %>"><img src="" width="24" height="24"></a>
                <a href="#"><img src="" width="24" height="24"></a>
                <a href="#"><img src="" width="24" height="24"></a>
                <a href="#"><img src="" width="24" height="24"></a>
              </li>
              <li>
                <label for="invite_key">
                  <span data-tooltip aria-haspopup="true" class="has-tip" title="Введя этот код при регистрации, новые пользователи смогут присоединиться к вам.">ваш код-приглашение</span>
                </label>
                <%= text_field_tag(:invite_key, current_user.user_hash) %>
              </li>

              <!-- <li class="share-to">
                <%= label_tag :share_email, 'отправить на' %>
                <div class="row collapse">
                  <div class="small-9 columns">
                    <%= text_field_tag :share_email, nil, { placeholder: "email" } %>
                  </div>
                  <div class="small-3 columns">
                    <%= submit_tag "Go", { class: "button postfix" } %>
                  </div>
                </div>
              </li> -->
            </ul>
          </li>
          <% end %>
          <% if signed_in? %>
            <li class="active has-dropdown">
              <%= link_to('Профиль', root_path) %>
              <ul class="dropdown">
                <% if current_user.admin? %>
                  <li>
                    <%= link_to('Список новостей', list_news_path) %>
                  </li>
                  <li>
                    <%= link_to('Список пользователей', users_path) %>
                  </li>
                  <li>
                    <%= link_to('Управление фондами', funds_path) %>
                  </li>
                  <li>
                    <%= link_to('Специальные ссылки', special_links_path) %>
                  </li>
                  <li>
                    <%= link_to('Статистика', statistics_path) %>
                  </li>
                <% end %>
                <% if confirmed? %>
                  <li>
                    <%= link_to 'Список приглашённых', invited_list_path %>
                  </li>
                  <!-- <li>
                    <a href="#">Ваши достижения</a>
                  </li> -->
                  <li>
                    <%= link_to 'Снять деньги', withdraw_path %>
                  </li>
                  <li>
                    <%= link_to 'Настройки', settings_path %>
                  </li>
                <% end %>
                <li>
                  <%= link_to('Выход', signout_path, method: "delete") %>
                </li>
              </ul>
            </li>
          <% else %>
            <li>
              <%= link_to('Вход', signin_path) %>
            </li>
          <% end %>
          <% unless signed_in? %>
            <li>
              <%= link_to('О проекте', how_it_work_path) %>
            </li>
          <% end %>
        </ul>
      </div>
    </section>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Happy Tree<%= content_for?(:title) ? " - " + yield(:title) : "" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
    <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js" %>
    
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div id="sky" class="background-pic"></div>
    <div id="sky-2" class="background-pic"></div>
    <div class="row">
      <%= render 'layouts/top_bar' %>
    </div>

    <div class="row content-bar">
      <%= render 'layouts/side_bar' if confirmed? %>
      <div class="medium-<%= confirmed? ? 9 : 12 %> columns">
        <span id="content">
          <% flash.each do |key, value| %>
            <%= content_tag(:div, value, class: "large-offset-3 large-6 alert-box #{key}") %>
          <% end %>
          <%= yield %>
          <%= debug(params) if Rails.env.development? %>
        </span>
      </div>
    </div>

    <div class="row" id="footer">
      <%= render 'layouts/footer' %>
    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>